Update Werkzeug to 1.0.1
This also resolves type error which was fixed in https://werkzeug.palletsprojects.com/en/1.0.x/changes/#version-0-15-5
Without this, the following traceback is observed:

```
/python/venv/lib/python3.8/site-packages/werkzeug/routing.py", line 951, in _compile_builder
    code = compile(module, "<werkzeug routing>", "exec")
TypeError: required field "type_ignores" missing from Modulew

```